### ISSUE TITLE
Flicker 4k

### ISSUE THREAD

**Issue by retomi** [xxxzc/xps15-9550-macos#18]
Hi, sometimes I have screen flicker problems, I think after standby but I have to investigate better. I have a 4k with i5.

**Comment by xxxzc** [comment]
So did I. You can try:

1. Use [Hackintool](https://www.tonymacx86.com/threads/release-hackintool-v2-4-6.254559/) to generate framebuffer patching. My config file don't include this because I can't confirm those values are constant for different situations. (e.g. hdmi or dp, 4k or 1080p).
2. Change `AAPL,ig-platform-id` to `AAAWGQ==`。`AAAbGQ==` (HD Graphics 530) is the model that 9550 is using. But in the old days, they usually use `AAAWGQ==` (HD Graphics 520) to represent Skylake i5 model, maybe they are experienced.
3. Investigate whether there is a hardware/video acceleration problem. I found my laptop been slow and hot when playing online video, maybe a acceleration problem? Was screen flickering occurred when using Chrome? Do disabling Chrome's hardware aaceleration works?

I have to use linux for study and development in recent days. Hopes you can find a solution :).

**Comment by retomi** [comment]
Hello,
unfortunately I don't know how to use Hackintool so I changed `AAPL, ig-platform-id` in `AAAWGQ ==`, I'll check if the problem still occurs.

thanks a lot

**Comment by retomi** [comment]
In the last release of the repo it seems solved.

**Comment by tiger511** [comment]
> So did I. You can try:
> 
> 1. Use [Hackintool](https://www.tonymacx86.com/threads/release-hackintool-v2-4-6.254559/) to generate framebuffer patching. My config file don't include this because I can't confirm those values are constant for different situations. (e.g. hdmi or dp, 4k or 1080p).
> 2. Change `AAPL,ig-platform-id` to `AAAWGQ==`。`AAAbGQ==` (HD Graphics 530) is the model that 9550 is using. But in the old days, they usually use `AAAWGQ==` (HD Graphics 520) to represent Skylake i5 model, maybe they are experienced.
> 3. Investigate whether there is a hardware/video acceleration problem. I found my laptop been slow and hot when playing online video, maybe a acceleration problem? Was screen flickering occurred when using Chrome? Do disabling Chrome's hardware aaceleration works?
> 
> I have to use linux for study and development in recent days. Hopes you can find a solution :).

The symptoms you mentioned are exactly the same.The problem is incompatible/Non apple Display.Overriding EDID solves problem.The tutorial to do that is mentioned in wmchris tutorial.
