### ISSUE TITLE
Config for Big sur Beta

### ISSUE THREAD

**Issue by imanng** [xxxzc/xps15-9550-macos#64]
Hi,
Do you config to support big sur beta?
I tried config, but when booting big sur, it doesn't work.

**Comment by ghost** [comment]
This is for macOS Catalina 10.15.6. Betas are obviously not supported yet.

**Comment by xxxzc** [comment]
Please refer to https://github.com/xxxzc/xps15-9570-macos#big-sur

I can OTA my 9570 from 10.15.6 to bigsur beta2 using a OC configuration similar to this repo. I am using SN550 instead of SM961/PM961(these two SSDs cannot OTA/install bigsur in my and some friends's test).

Please post on screen error log, I will help you.

**Comment by imanng** [comment]
I'll try it!

**Comment by imanng** [comment]
I followed this guide. it works perfect.
https://github.com/xxxzc/xps15-9570-macos/issues/59

![image](https://user-images.githubusercontent.com/39839527/95401727-319b1e00-0938-11eb-8c6b-4037f8b63bfc.png)
